version: "3.8"
services:
  boilerplate_app:
    container_name: boilerplate_app
    build: ./
    command: npm run dev
    ports: 
      - 8080:8080
    restart: always
    volumes:
      - ./src:/app/src
    networks:
      - boilerplate_network
  database:
    container_name: database
    image: postgres:12
    restart: always
    tty: true
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data/
    networks:
      - boilerplate_network
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=boilerplate
networks:
  boilerplate_network:
    name: boilerplate_network
    driver: bridge