version: "3.8"
services:
  app:
    container_name: boilerplate
    build: ./
    command: npm start
    ports: 
      - 8080:8080
    restart: always
    volumes:
      - ./src:/app/src
    networks:
      - boilerplate_network
networks:
  boilerplate_network:
    name: boilerplate_network
    driver: bridge