version: "3.8"
services:
  boilerplate_app:
    container_name: boilerplate_app
    build: ./
    command: npm start
    ports: 
      - ${APP_PORT}:${APP_PORT}
    restart: always
    volumes:
      - ./src:/app/src
    networks:
      - boilerplate_network
  database:
    container_name: database
    image: postgres:15
    restart: always
    tty: true
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ./data:/var/lib/postgresql/data/
    networks:
      - boilerplate_network
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
networks:
  boilerplate_network:
    name: boilerplate_network
    driver: bridge